spring:
  application:
    name: ${APP_NAME:hz-service}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/changelog-master.xml
    driver-class-name: org.postgresql.Driver

  cache:
    type: hazelcast
    cache-names: orders

  hazelcast:
    config: classpath:hazelcast-client.yaml

server:
  port: ${SERVER_PORT:8081}

management:
  server:
    port: ${MANAGEMENT_PORT:8084}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    cache:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
