global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cf-db-service-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cf-service-1:8084']
  - job_name: 'cf-db-service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cf-service-2:8085']