spring:
  application:
    name: ${APP_NAME:redis-service}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/changelog-master.xml
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
    cache-names: orders
    redis:
      key-prefix: "order_"
      cache-null-values: false
  data:
    redis:
      host: localhost
      port: 6379
      client-type: jedis
      client-name: redis-service

server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: ${MANAGEMENT_PORT:8084}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    cache:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
