spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    name: postgres
    url: jdbc:postgresql://postgres:5432/postgres

  liquibase:
    url: jdbc:postgresql://postgres:5432/postgres
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/changelog-master.xml
    driver-class-name: org.postgresql.Driver

  cache:
    type: caffeine
    cache-names: orders
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ${KAFKA_CG_NAME:cf-kafka-service-2}
      auto-offset-reset: latest
    producer:
      bootstrap-servers: kafka:9092
